# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/software-ventilador/ui/GUI_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Respirador(object):
    def setupUi(self, Respirador):
        Respirador.setObjectName("Respirador")
        Respirador.resize(1024, 600)
        Respirador.setMinimumSize(QtCore.QSize(600, 400))
        Respirador.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralWidget = QtWidgets.QWidget(Respirador)
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.volume_graph_VBox = QtWidgets.QVBoxLayout()
        self.volume_graph_VBox.setObjectName("volume_graph_VBox")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.volume_graph_VBox.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.volume_graph_VBox)
        self.flow_graph_VBox = QtWidgets.QVBoxLayout()
        self.flow_graph_VBox.setObjectName("flow_graph_VBox")
        self.verticalLayout_4.addLayout(self.flow_graph_VBox)
        self.pressure_graph_VBox = QtWidgets.QVBoxLayout()
        self.pressure_graph_VBox.setObjectName("pressure_graph_VBox")
        self.verticalLayout_4.addLayout(self.pressure_graph_VBox)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.VCV_tab = QtWidgets.QWidget()
        self.VCV_tab.setObjectName("VCV_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.VCV_tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.VCV_volume_lbl = QtWidgets.QLabel(self.VCV_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VCV_volume_lbl.sizePolicy().hasHeightForWidth())
        self.VCV_volume_lbl.setSizePolicy(sizePolicy)
        self.VCV_volume_lbl.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_volume_lbl.setFont(font)
        self.VCV_volume_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.VCV_volume_lbl.setObjectName("VCV_volume_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.VCV_volume_lbl)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.VCV_volume_minus = QtWidgets.QPushButton(self.VCV_tab)
        self.VCV_volume_minus.setMinimumSize(QtCore.QSize(30, 30))
        self.VCV_volume_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_volume_minus.setFont(font)
        self.VCV_volume_minus.setObjectName("VCV_volume_minus")
        self.horizontalLayout_3.addWidget(self.VCV_volume_minus)
        self.VCV_volume_val = QtWidgets.QLabel(self.VCV_tab)
        self.VCV_volume_val.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_volume_val.setFont(font)
        self.VCV_volume_val.setObjectName("VCV_volume_val")
        self.horizontalLayout_3.addWidget(self.VCV_volume_val)
        self.VCV_volume_plus = QtWidgets.QPushButton(self.VCV_tab)
        self.VCV_volume_plus.setMinimumSize(QtCore.QSize(30, 30))
        self.VCV_volume_plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_volume_plus.setFont(font)
        self.VCV_volume_plus.setObjectName("VCV_volume_plus")
        self.horizontalLayout_3.addWidget(self.VCV_volume_plus)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.VCV_frequency_lbl = QtWidgets.QLabel(self.VCV_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VCV_frequency_lbl.sizePolicy().hasHeightForWidth())
        self.VCV_frequency_lbl.setSizePolicy(sizePolicy)
        self.VCV_frequency_lbl.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_frequency_lbl.setFont(font)
        self.VCV_frequency_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.VCV_frequency_lbl.setObjectName("VCV_frequency_lbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.VCV_frequency_lbl)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.VCV_frequency_minus = QtWidgets.QPushButton(self.VCV_tab)
        self.VCV_frequency_minus.setMinimumSize(QtCore.QSize(30, 30))
        self.VCV_frequency_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_frequency_minus.setFont(font)
        self.VCV_frequency_minus.setObjectName("VCV_frequency_minus")
        self.horizontalLayout_2.addWidget(self.VCV_frequency_minus)
        self.VCV_frequency_val = QtWidgets.QLabel(self.VCV_tab)
        self.VCV_frequency_val.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_frequency_val.setFont(font)
        self.VCV_frequency_val.setObjectName("VCV_frequency_val")
        self.horizontalLayout_2.addWidget(self.VCV_frequency_val)
        self.VCV_frequency_plus = QtWidgets.QPushButton(self.VCV_tab)
        self.VCV_frequency_plus.setMinimumSize(QtCore.QSize(30, 30))
        self.VCV_frequency_plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_frequency_plus.setFont(font)
        self.VCV_frequency_plus.setObjectName("VCV_frequency_plus")
        self.horizontalLayout_2.addWidget(self.VCV_frequency_plus)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.VCV_flow_lbl = QtWidgets.QLabel(self.VCV_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VCV_flow_lbl.sizePolicy().hasHeightForWidth())
        self.VCV_flow_lbl.setSizePolicy(sizePolicy)
        self.VCV_flow_lbl.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_flow_lbl.setFont(font)
        self.VCV_flow_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.VCV_flow_lbl.setObjectName("VCV_flow_lbl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.VCV_flow_lbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.VCV_flow_minus = QtWidgets.QPushButton(self.VCV_tab)
        self.VCV_flow_minus.setMinimumSize(QtCore.QSize(30, 30))
        self.VCV_flow_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_flow_minus.setFont(font)
        self.VCV_flow_minus.setObjectName("VCV_flow_minus")
        self.horizontalLayout.addWidget(self.VCV_flow_minus)
        self.VCV_flow_val = QtWidgets.QLabel(self.VCV_tab)
        self.VCV_flow_val.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_flow_val.setFont(font)
        self.VCV_flow_val.setObjectName("VCV_flow_val")
        self.horizontalLayout.addWidget(self.VCV_flow_val)
        self.VCV_flow_plus = QtWidgets.QPushButton(self.VCV_tab)
        self.VCV_flow_plus.setMinimumSize(QtCore.QSize(30, 30))
        self.VCV_flow_plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_flow_plus.setFont(font)
        self.VCV_flow_plus.setObjectName("VCV_flow_plus")
        self.horizontalLayout.addWidget(self.VCV_flow_plus)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.VCV_inhale_pause_btn = QtWidgets.QPushButton(self.VCV_tab)
        self.VCV_inhale_pause_btn.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_inhale_pause_btn.setFont(font)
        self.VCV_inhale_pause_btn.setObjectName("VCV_inhale_pause_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.VCV_inhale_pause_btn)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.VCV_inhale_pause_minus = QtWidgets.QPushButton(self.VCV_tab)
        self.VCV_inhale_pause_minus.setMinimumSize(QtCore.QSize(30, 30))
        self.VCV_inhale_pause_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_inhale_pause_minus.setFont(font)
        self.VCV_inhale_pause_minus.setObjectName("VCV_inhale_pause_minus")
        self.horizontalLayout_5.addWidget(self.VCV_inhale_pause_minus)
        self.VCV_inhale_pause_val = QtWidgets.QLabel(self.VCV_tab)
        self.VCV_inhale_pause_val.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_inhale_pause_val.setFont(font)
        self.VCV_inhale_pause_val.setObjectName("VCV_inhale_pause_val")
        self.horizontalLayout_5.addWidget(self.VCV_inhale_pause_val)
        self.VCV_inhale_pause_plus = QtWidgets.QPushButton(self.VCV_tab)
        self.VCV_inhale_pause_plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_inhale_pause_plus.setFont(font)
        self.VCV_inhale_pause_plus.setObjectName("VCV_inhale_pause_plus")
        self.horizontalLayout_5.addWidget(self.VCV_inhale_pause_plus)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.VCV_start_btn = QtWidgets.QPushButton(self.VCV_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VCV_start_btn.sizePolicy().hasHeightForWidth())
        self.VCV_start_btn.setSizePolicy(sizePolicy)
        self.VCV_start_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.VCV_start_btn.setSizeIncrement(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_start_btn.setFont(font)
        self.VCV_start_btn.setObjectName("VCV_start_btn")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.VCV_start_btn)
        self.VCV_stop_btn = QtWidgets.QPushButton(self.VCV_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VCV_stop_btn.sizePolicy().hasHeightForWidth())
        self.VCV_stop_btn.setSizePolicy(sizePolicy)
        self.VCV_stop_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.VCV_stop_btn.setSizeIncrement(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.VCV_stop_btn.setFont(font)
        self.VCV_stop_btn.setObjectName("VCV_stop_btn")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.VCV_stop_btn)
        self.verticalLayout_9.addLayout(self.formLayout)
        self.tabWidget.addTab(self.VCV_tab, "")
        self.PCV_tab = QtWidgets.QWidget()
        self.PCV_tab.setObjectName("PCV_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.PCV_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.PCV_pressure_lbl = QtWidgets.QLabel(self.PCV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_pressure_lbl.setFont(font)
        self.PCV_pressure_lbl.setObjectName("PCV_pressure_lbl")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.PCV_pressure_lbl)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.PCV_pressure_minus = QtWidgets.QPushButton(self.PCV_tab)
        self.PCV_pressure_minus.setMinimumSize(QtCore.QSize(30, 30))
        self.PCV_pressure_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_pressure_minus.setFont(font)
        self.PCV_pressure_minus.setObjectName("PCV_pressure_minus")
        self.horizontalLayout_10.addWidget(self.PCV_pressure_minus)
        self.PCV_pressure_val = QtWidgets.QLabel(self.PCV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_pressure_val.setFont(font)
        self.PCV_pressure_val.setObjectName("PCV_pressure_val")
        self.horizontalLayout_10.addWidget(self.PCV_pressure_val)
        self.PCV_pressure_plus = QtWidgets.QPushButton(self.PCV_tab)
        self.PCV_pressure_plus.setMinimumSize(QtCore.QSize(30, 30))
        self.PCV_pressure_plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_pressure_plus.setFont(font)
        self.PCV_pressure_plus.setObjectName("PCV_pressure_plus")
        self.horizontalLayout_10.addWidget(self.PCV_pressure_plus)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.PCV_frequency_lbl = QtWidgets.QLabel(self.PCV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_frequency_lbl.setFont(font)
        self.PCV_frequency_lbl.setObjectName("PCV_frequency_lbl")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.PCV_frequency_lbl)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.PCV_frequency_minus = QtWidgets.QPushButton(self.PCV_tab)
        self.PCV_frequency_minus.setMinimumSize(QtCore.QSize(30, 30))
        self.PCV_frequency_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_frequency_minus.setFont(font)
        self.PCV_frequency_minus.setObjectName("PCV_frequency_minus")
        self.horizontalLayout_7.addWidget(self.PCV_frequency_minus)
        self.PCV_frequency_val = QtWidgets.QLabel(self.PCV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_frequency_val.setFont(font)
        self.PCV_frequency_val.setObjectName("PCV_frequency_val")
        self.horizontalLayout_7.addWidget(self.PCV_frequency_val)
        self.PCV_frequency_plus = QtWidgets.QPushButton(self.PCV_tab)
        self.PCV_frequency_plus.setMinimumSize(QtCore.QSize(30, 30))
        self.PCV_frequency_plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_frequency_plus.setFont(font)
        self.PCV_frequency_plus.setObjectName("PCV_frequency_plus")
        self.horizontalLayout_7.addWidget(self.PCV_frequency_plus)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.PCV_inhale_time_lbl = QtWidgets.QLabel(self.PCV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_inhale_time_lbl.setFont(font)
        self.PCV_inhale_time_lbl.setObjectName("PCV_inhale_time_lbl")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.PCV_inhale_time_lbl)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.PCV_inhale_time_minus = QtWidgets.QPushButton(self.PCV_tab)
        self.PCV_inhale_time_minus.setMinimumSize(QtCore.QSize(30, 30))
        self.PCV_inhale_time_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_inhale_time_minus.setFont(font)
        self.PCV_inhale_time_minus.setObjectName("PCV_inhale_time_minus")
        self.horizontalLayout_9.addWidget(self.PCV_inhale_time_minus)
        self.PCV_inhale_time_val = QtWidgets.QLabel(self.PCV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_inhale_time_val.setFont(font)
        self.PCV_inhale_time_val.setObjectName("PCV_inhale_time_val")
        self.horizontalLayout_9.addWidget(self.PCV_inhale_time_val)
        self.PCV_inhale_time_plus = QtWidgets.QPushButton(self.PCV_tab)
        self.PCV_inhale_time_plus.setMinimumSize(QtCore.QSize(30, 30))
        self.PCV_inhale_time_plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_inhale_time_plus.setFont(font)
        self.PCV_inhale_time_plus.setObjectName("PCV_inhale_time_plus")
        self.horizontalLayout_9.addWidget(self.PCV_inhale_time_plus)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.PCV_rise_time_lbl = QtWidgets.QLabel(self.PCV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_rise_time_lbl.setFont(font)
        self.PCV_rise_time_lbl.setObjectName("PCV_rise_time_lbl")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.PCV_rise_time_lbl)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PCV_rise_time_minus = QtWidgets.QPushButton(self.PCV_tab)
        self.PCV_rise_time_minus.setMinimumSize(QtCore.QSize(30, 30))
        self.PCV_rise_time_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_rise_time_minus.setFont(font)
        self.PCV_rise_time_minus.setObjectName("PCV_rise_time_minus")
        self.horizontalLayout_4.addWidget(self.PCV_rise_time_minus)
        self.PCV_rise_time_val = QtWidgets.QLabel(self.PCV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_rise_time_val.setFont(font)
        self.PCV_rise_time_val.setObjectName("PCV_rise_time_val")
        self.horizontalLayout_4.addWidget(self.PCV_rise_time_val)
        self.PCV_rise_time_plus = QtWidgets.QPushButton(self.PCV_tab)
        self.PCV_rise_time_plus.setMinimumSize(QtCore.QSize(30, 30))
        self.PCV_rise_time_plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_rise_time_plus.setFont(font)
        self.PCV_rise_time_plus.setObjectName("PCV_rise_time_plus")
        self.horizontalLayout_4.addWidget(self.PCV_rise_time_plus)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.PCV_start_btn = QtWidgets.QPushButton(self.PCV_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PCV_start_btn.sizePolicy().hasHeightForWidth())
        self.PCV_start_btn.setSizePolicy(sizePolicy)
        self.PCV_start_btn.setMinimumSize(QtCore.QSize(90, 50))
        self.PCV_start_btn.setSizeIncrement(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_start_btn.setFont(font)
        self.PCV_start_btn.setObjectName("PCV_start_btn")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.PCV_start_btn)
        self.PCV_stop_bnt = QtWidgets.QPushButton(self.PCV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_stop_bnt.setFont(font)
        self.PCV_stop_bnt.setObjectName("PCV_stop_bnt")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.PCV_stop_bnt)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.PCV_inhale_pause_minus = QtWidgets.QPushButton(self.PCV_tab)
        self.PCV_inhale_pause_minus.setMinimumSize(QtCore.QSize(30, 30))
        self.PCV_inhale_pause_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_inhale_pause_minus.setFont(font)
        self.PCV_inhale_pause_minus.setObjectName("PCV_inhale_pause_minus")
        self.horizontalLayout_6.addWidget(self.PCV_inhale_pause_minus)
        self.PCV_inhale_pause_val = QtWidgets.QLabel(self.PCV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_inhale_pause_val.setFont(font)
        self.PCV_inhale_pause_val.setObjectName("PCV_inhale_pause_val")
        self.horizontalLayout_6.addWidget(self.PCV_inhale_pause_val)
        self.PCV_inhale_pause_plus = QtWidgets.QPushButton(self.PCV_tab)
        self.PCV_inhale_pause_plus.setMinimumSize(QtCore.QSize(30, 30))
        self.PCV_inhale_pause_plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_inhale_pause_plus.setFont(font)
        self.PCV_inhale_pause_plus.setObjectName("PCV_inhale_pause_plus")
        self.horizontalLayout_6.addWidget(self.PCV_inhale_pause_plus)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.PCV_inhale_pause_btn = QtWidgets.QPushButton(self.PCV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PCV_inhale_pause_btn.setFont(font)
        self.PCV_inhale_pause_btn.setObjectName("PCV_inhale_pause_btn")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.PCV_inhale_pause_btn)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.tabWidget.addTab(self.PCV_tab, "")
        self.PSV_tab = QtWidgets.QWidget()
        self.PSV_tab.setObjectName("PSV_tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.PSV_tab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.PSV_support_pressure_lbl = QtWidgets.QLabel(self.PSV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_support_pressure_lbl.setFont(font)
        self.PSV_support_pressure_lbl.setObjectName("PSV_support_pressure_lbl")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.PSV_support_pressure_lbl)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.PSV_pressure_minus = QtWidgets.QPushButton(self.PSV_tab)
        self.PSV_pressure_minus.setMinimumSize(QtCore.QSize(30, 30))
        self.PSV_pressure_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_pressure_minus.setFont(font)
        self.PSV_pressure_minus.setObjectName("PSV_pressure_minus")
        self.horizontalLayout_11.addWidget(self.PSV_pressure_minus)
        self.PSV_pressure_val = QtWidgets.QLabel(self.PSV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_pressure_val.setFont(font)
        self.PSV_pressure_val.setObjectName("PSV_pressure_val")
        self.horizontalLayout_11.addWidget(self.PSV_pressure_val)
        self.PSV_pressure_plus = QtWidgets.QPushButton(self.PSV_tab)
        self.PSV_pressure_plus.setMinimumSize(QtCore.QSize(30, 30))
        self.PSV_pressure_plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_pressure_plus.setFont(font)
        self.PSV_pressure_plus.setObjectName("PSV_pressure_plus")
        self.horizontalLayout_11.addWidget(self.PSV_pressure_plus)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.PSV_rise_time_lbl = QtWidgets.QLabel(self.PSV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_rise_time_lbl.setFont(font)
        self.PSV_rise_time_lbl.setObjectName("PSV_rise_time_lbl")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.PSV_rise_time_lbl)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.PSV_rise_time_minus = QtWidgets.QPushButton(self.PSV_tab)
        self.PSV_rise_time_minus.setMinimumSize(QtCore.QSize(30, 30))
        self.PSV_rise_time_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_rise_time_minus.setFont(font)
        self.PSV_rise_time_minus.setObjectName("PSV_rise_time_minus")
        self.horizontalLayout_12.addWidget(self.PSV_rise_time_minus)
        self.PSV_rise_time_val = QtWidgets.QLabel(self.PSV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_rise_time_val.setFont(font)
        self.PSV_rise_time_val.setObjectName("PSV_rise_time_val")
        self.horizontalLayout_12.addWidget(self.PSV_rise_time_val)
        self.PSV_rise_time_plus = QtWidgets.QPushButton(self.PSV_tab)
        self.PSV_rise_time_plus.setMinimumSize(QtCore.QSize(30, 30))
        self.PSV_rise_time_plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_rise_time_plus.setFont(font)
        self.PSV_rise_time_plus.setObjectName("PSV_rise_time_plus")
        self.horizontalLayout_12.addWidget(self.PSV_rise_time_plus)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.PSV_start_btn = QtWidgets.QPushButton(self.PSV_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PSV_start_btn.sizePolicy().hasHeightForWidth())
        self.PSV_start_btn.setSizePolicy(sizePolicy)
        self.PSV_start_btn.setMinimumSize(QtCore.QSize(90, 50))
        self.PSV_start_btn.setSizeIncrement(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_start_btn.setFont(font)
        self.PSV_start_btn.setObjectName("PSV_start_btn")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.PSV_start_btn)
        self.PSV_stop_btn = QtWidgets.QPushButton(self.PSV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_stop_btn.setFont(font)
        self.PSV_stop_btn.setObjectName("PSV_stop_btn")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.PSV_stop_btn)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.PSV_inhale_pause_minus = QtWidgets.QPushButton(self.PSV_tab)
        self.PSV_inhale_pause_minus.setMinimumSize(QtCore.QSize(30, 30))
        self.PSV_inhale_pause_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_inhale_pause_minus.setFont(font)
        self.PSV_inhale_pause_minus.setObjectName("PSV_inhale_pause_minus")
        self.horizontalLayout_13.addWidget(self.PSV_inhale_pause_minus)
        self.PSV_inhale_pause_val = QtWidgets.QLabel(self.PSV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_inhale_pause_val.setFont(font)
        self.PSV_inhale_pause_val.setObjectName("PSV_inhale_pause_val")
        self.horizontalLayout_13.addWidget(self.PSV_inhale_pause_val)
        self.PSV_inhale_pause_plus = QtWidgets.QPushButton(self.PSV_tab)
        self.PSV_inhale_pause_plus.setMinimumSize(QtCore.QSize(30, 30))
        self.PSV_inhale_pause_plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_inhale_pause_plus.setFont(font)
        self.PSV_inhale_pause_plus.setObjectName("PSV_inhale_pause_plus")
        self.horizontalLayout_13.addWidget(self.PSV_inhale_pause_plus)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.PSV_inhale_pause_btn = QtWidgets.QPushButton(self.PSV_tab)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.PSV_inhale_pause_btn.setFont(font)
        self.PSV_inhale_pause_btn.setObjectName("PSV_inhale_pause_btn")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.PSV_inhale_pause_btn)
        self.verticalLayout_10.addLayout(self.formLayout_4)
        self.tabWidget.addTab(self.PSV_tab, "")
        self.alarms_tab = QtWidgets.QWidget()
        self.alarms_tab.setObjectName("alarms_tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.alarms_tab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.al_paw_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_paw_chkBox.setFont(font)
        self.al_paw_chkBox.setObjectName("al_paw_chkBox")
        self.gridLayout_2.addWidget(self.al_paw_chkBox, 4, 0, 1, 1)
        self.al_apnea_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_apnea_chkBox.setFont(font)
        self.al_apnea_chkBox.setObjectName("al_apnea_chkBox")
        self.gridLayout_2.addWidget(self.al_apnea_chkBox, 8, 0, 1, 1)
        self.al_plateau_pressure_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_plateau_pressure_chkBox.setFont(font)
        self.al_plateau_pressure_chkBox.setObjectName("al_plateau_pressure_chkBox")
        self.gridLayout_2.addWidget(self.al_plateau_pressure_chkBox, 5, 0, 1, 1)
        self.al_frequency_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_frequency_chkBox.setFont(font)
        self.al_frequency_chkBox.setObjectName("al_frequency_chkBox")
        self.gridLayout_2.addWidget(self.al_frequency_chkBox, 7, 0, 1, 1)
        self.al_paw_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_paw_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_paw_ok_btn.setSizePolicy(sizePolicy)
        self.al_paw_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_paw_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_paw_ok_btn.setFont(font)
        self.al_paw_ok_btn.setObjectName("al_paw_ok_btn")
        self.gridLayout_2.addWidget(self.al_paw_ok_btn, 4, 3, 1, 1)
        self.al_frequency_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_frequency_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_frequency_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_frequency_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_frequency_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_frequency_max_dSpinBox.setFont(font)
        self.al_frequency_max_dSpinBox.setDecimals(1)
        self.al_frequency_max_dSpinBox.setMaximum(100000.0)
        self.al_frequency_max_dSpinBox.setSingleStep(0.1)
        self.al_frequency_max_dSpinBox.setObjectName("al_frequency_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_frequency_max_dSpinBox, 7, 2, 1, 1)
        self.al_plateau_pressure_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_plateau_pressure_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_plateau_pressure_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_plateau_pressure_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_plateau_pressure_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_plateau_pressure_max_dSpinBox.setFont(font)
        self.al_plateau_pressure_max_dSpinBox.setDecimals(1)
        self.al_plateau_pressure_max_dSpinBox.setMaximum(100000.0)
        self.al_plateau_pressure_max_dSpinBox.setSingleStep(0.1)
        self.al_plateau_pressure_max_dSpinBox.setObjectName("al_plateau_pressure_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_plateau_pressure_max_dSpinBox, 5, 2, 1, 1)
        self.al_volume_minute_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_volume_minute_chkBox.setFont(font)
        self.al_volume_minute_chkBox.setObjectName("al_volume_minute_chkBox")
        self.gridLayout_2.addWidget(self.al_volume_minute_chkBox, 2, 0, 1, 1)
        self.al_plateau_pressure_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_plateau_pressure_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_plateau_pressure_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_plateau_pressure_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_plateau_pressure_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_plateau_pressure_min_dSpinBox.setFont(font)
        self.al_plateau_pressure_min_dSpinBox.setDecimals(1)
        self.al_plateau_pressure_min_dSpinBox.setMaximum(100000.0)
        self.al_plateau_pressure_min_dSpinBox.setSingleStep(0.1)
        self.al_plateau_pressure_min_dSpinBox.setObjectName("al_plateau_pressure_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_plateau_pressure_min_dSpinBox, 5, 1, 1, 1)
        self.al_tidal_volume_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_tidal_volume_chkBox.setFont(font)
        self.al_tidal_volume_chkBox.setObjectName("al_tidal_volume_chkBox")
        self.gridLayout_2.addWidget(self.al_tidal_volume_chkBox, 1, 0, 1, 1)
        self.al_tidal_volume_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_tidal_volume_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_tidal_volume_ok_btn.setSizePolicy(sizePolicy)
        self.al_tidal_volume_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_tidal_volume_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_tidal_volume_ok_btn.setFont(font)
        self.al_tidal_volume_ok_btn.setObjectName("al_tidal_volume_ok_btn")
        self.gridLayout_2.addWidget(self.al_tidal_volume_ok_btn, 1, 3, 1, 1)
        self.al_flow_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_flow_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_flow_ok_btn.setSizePolicy(sizePolicy)
        self.al_flow_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_flow_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_flow_ok_btn.setFont(font)
        self.al_flow_ok_btn.setObjectName("al_flow_ok_btn")
        self.gridLayout_2.addWidget(self.al_flow_ok_btn, 3, 3, 1, 1)
        self.al_apnea_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_apnea_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_apnea_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_apnea_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_apnea_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_apnea_max_dSpinBox.setFont(font)
        self.al_apnea_max_dSpinBox.setDecimals(1)
        self.al_apnea_max_dSpinBox.setMaximum(100000.0)
        self.al_apnea_max_dSpinBox.setSingleStep(0.1)
        self.al_apnea_max_dSpinBox.setObjectName("al_apnea_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_apnea_max_dSpinBox, 8, 2, 1, 1)
        self.al_volume_minute_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_volume_minute_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_volume_minute_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_volume_minute_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_volume_minute_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_volume_minute_min_dSpinBox.setFont(font)
        self.al_volume_minute_min_dSpinBox.setDecimals(1)
        self.al_volume_minute_min_dSpinBox.setMaximum(100000.0)
        self.al_volume_minute_min_dSpinBox.setSingleStep(0.1)
        self.al_volume_minute_min_dSpinBox.setObjectName("al_volume_minute_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_volume_minute_min_dSpinBox, 2, 1, 1, 1)
        self.al_flow_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_flow_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_flow_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_flow_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_flow_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_flow_min_dSpinBox.setFont(font)
        self.al_flow_min_dSpinBox.setDecimals(1)
        self.al_flow_min_dSpinBox.setMaximum(100000.0)
        self.al_flow_min_dSpinBox.setSingleStep(0.1)
        self.al_flow_min_dSpinBox.setObjectName("al_flow_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_flow_min_dSpinBox, 3, 1, 1, 1)
        self.al_flow_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_flow_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_flow_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_flow_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_flow_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_flow_max_dSpinBox.setFont(font)
        self.al_flow_max_dSpinBox.setDecimals(1)
        self.al_flow_max_dSpinBox.setMaximum(100000.0)
        self.al_flow_max_dSpinBox.setSingleStep(0.1)
        self.al_flow_max_dSpinBox.setObjectName("al_flow_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_flow_max_dSpinBox, 3, 2, 1, 1)
        self.al_tidal_volume_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_tidal_volume_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_tidal_volume_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_tidal_volume_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_tidal_volume_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_tidal_volume_max_dSpinBox.setFont(font)
        self.al_tidal_volume_max_dSpinBox.setDecimals(1)
        self.al_tidal_volume_max_dSpinBox.setMaximum(100000.0)
        self.al_tidal_volume_max_dSpinBox.setSingleStep(0.1)
        self.al_tidal_volume_max_dSpinBox.setObjectName("al_tidal_volume_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_tidal_volume_max_dSpinBox, 1, 2, 1, 1)
        self.al_volume_minute_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_volume_minute_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_volume_minute_ok_btn.setSizePolicy(sizePolicy)
        self.al_volume_minute_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_volume_minute_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_volume_minute_ok_btn.setFont(font)
        self.al_volume_minute_ok_btn.setObjectName("al_volume_minute_ok_btn")
        self.gridLayout_2.addWidget(self.al_volume_minute_ok_btn, 2, 3, 1, 1)
        self.al_frequency_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_frequency_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_frequency_ok_btn.setSizePolicy(sizePolicy)
        self.al_frequency_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_frequency_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_frequency_ok_btn.setFont(font)
        self.al_frequency_ok_btn.setObjectName("al_frequency_ok_btn")
        self.gridLayout_2.addWidget(self.al_frequency_ok_btn, 7, 3, 1, 1)
        self.al_paw_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_paw_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_paw_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_paw_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_paw_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_paw_max_dSpinBox.setFont(font)
        self.al_paw_max_dSpinBox.setDecimals(1)
        self.al_paw_max_dSpinBox.setMaximum(100000.0)
        self.al_paw_max_dSpinBox.setSingleStep(0.1)
        self.al_paw_max_dSpinBox.setObjectName("al_paw_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_paw_max_dSpinBox, 4, 2, 1, 1)
        self.al_frequency_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_frequency_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_frequency_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_frequency_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_frequency_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_frequency_min_dSpinBox.setFont(font)
        self.al_frequency_min_dSpinBox.setDecimals(1)
        self.al_frequency_min_dSpinBox.setMaximum(100000.0)
        self.al_frequency_min_dSpinBox.setSingleStep(0.1)
        self.al_frequency_min_dSpinBox.setObjectName("al_frequency_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_frequency_min_dSpinBox, 7, 1, 1, 1)
        self.al_PEEP_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_PEEP_chkBox.setFont(font)
        self.al_PEEP_chkBox.setObjectName("al_PEEP_chkBox")
        self.gridLayout_2.addWidget(self.al_PEEP_chkBox, 6, 0, 1, 1)
        self.al_flow_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_flow_chkBox.setFont(font)
        self.al_flow_chkBox.setObjectName("al_flow_chkBox")
        self.gridLayout_2.addWidget(self.al_flow_chkBox, 3, 0, 1, 1)
        self.al_tidal_volume_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_tidal_volume_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_tidal_volume_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_tidal_volume_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_tidal_volume_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_tidal_volume_min_dSpinBox.setFont(font)
        self.al_tidal_volume_min_dSpinBox.setDecimals(1)
        self.al_tidal_volume_min_dSpinBox.setMaximum(100000.0)
        self.al_tidal_volume_min_dSpinBox.setSingleStep(0.1)
        self.al_tidal_volume_min_dSpinBox.setObjectName("al_tidal_volume_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_tidal_volume_min_dSpinBox, 1, 1, 1, 1)
        self.al_PEEP_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_PEEP_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_PEEP_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_PEEP_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_PEEP_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_PEEP_max_dSpinBox.setFont(font)
        self.al_PEEP_max_dSpinBox.setDecimals(1)
        self.al_PEEP_max_dSpinBox.setMaximum(100000.0)
        self.al_PEEP_max_dSpinBox.setSingleStep(0.1)
        self.al_PEEP_max_dSpinBox.setObjectName("al_PEEP_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_PEEP_max_dSpinBox, 6, 2, 1, 1)
        self.al_plateau_pressure_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_plateau_pressure_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_plateau_pressure_ok_btn.setSizePolicy(sizePolicy)
        self.al_plateau_pressure_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_plateau_pressure_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_plateau_pressure_ok_btn.setFont(font)
        self.al_plateau_pressure_ok_btn.setObjectName("al_plateau_pressure_ok_btn")
        self.gridLayout_2.addWidget(self.al_plateau_pressure_ok_btn, 5, 3, 1, 1)
        self.al_PEEP_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_PEEP_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_PEEP_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_PEEP_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_PEEP_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_PEEP_min_dSpinBox.setFont(font)
        self.al_PEEP_min_dSpinBox.setDecimals(1)
        self.al_PEEP_min_dSpinBox.setMaximum(100000.0)
        self.al_PEEP_min_dSpinBox.setSingleStep(0.1)
        self.al_PEEP_min_dSpinBox.setObjectName("al_PEEP_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_PEEP_min_dSpinBox, 6, 1, 1, 1)
        self.al_apnea_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_apnea_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_apnea_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_apnea_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_apnea_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_apnea_min_dSpinBox.setFont(font)
        self.al_apnea_min_dSpinBox.setDecimals(1)
        self.al_apnea_min_dSpinBox.setMaximum(100000.0)
        self.al_apnea_min_dSpinBox.setSingleStep(0.1)
        self.al_apnea_min_dSpinBox.setObjectName("al_apnea_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_apnea_min_dSpinBox, 8, 1, 1, 1)
        self.al_volume_minute_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_volume_minute_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_volume_minute_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_volume_minute_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_volume_minute_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_volume_minute_max_dSpinBox.setFont(font)
        self.al_volume_minute_max_dSpinBox.setDecimals(1)
        self.al_volume_minute_max_dSpinBox.setMaximum(100000.0)
        self.al_volume_minute_max_dSpinBox.setSingleStep(0.1)
        self.al_volume_minute_max_dSpinBox.setObjectName("al_volume_minute_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_volume_minute_max_dSpinBox, 2, 2, 1, 1)
        self.al_PEEP_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_PEEP_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_PEEP_ok_btn.setSizePolicy(sizePolicy)
        self.al_PEEP_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_PEEP_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_PEEP_ok_btn.setFont(font)
        self.al_PEEP_ok_btn.setObjectName("al_PEEP_ok_btn")
        self.gridLayout_2.addWidget(self.al_PEEP_ok_btn, 6, 3, 1, 1)
        self.al_paw_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_paw_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_paw_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_paw_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_paw_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_paw_min_dSpinBox.setFont(font)
        self.al_paw_min_dSpinBox.setDecimals(1)
        self.al_paw_min_dSpinBox.setMaximum(100000.0)
        self.al_paw_min_dSpinBox.setSingleStep(0.1)
        self.al_paw_min_dSpinBox.setObjectName("al_paw_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_paw_min_dSpinBox, 4, 1, 1, 1)
        self.al_apnea_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_apnea_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_apnea_ok_btn.setSizePolicy(sizePolicy)
        self.al_apnea_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_apnea_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_apnea_ok_btn.setFont(font)
        self.al_apnea_ok_btn.setObjectName("al_apnea_ok_btn")
        self.gridLayout_2.addWidget(self.al_apnea_ok_btn, 8, 3, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.alarms_tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.inhale_time_lbl = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.inhale_time_lbl.setFont(font)
        self.inhale_time_lbl.setObjectName("inhale_time_lbl")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inhale_time_lbl)
        self.inhale_time_val = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.inhale_time_val.setFont(font)
        self.inhale_time_val.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inhale_time_val.setFrameShadow(QtWidgets.QFrame.Plain)
        self.inhale_time_val.setObjectName("inhale_time_val")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inhale_time_val)
        self.exhale_time_lbl = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.exhale_time_lbl.setFont(font)
        self.exhale_time_lbl.setObjectName("exhale_time_lbl")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.exhale_time_lbl)
        self.IE_ratio_lbl = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.IE_ratio_lbl.setFont(font)
        self.IE_ratio_lbl.setObjectName("IE_ratio_lbl")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.IE_ratio_lbl)
        self.IE_ratio_val = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.IE_ratio_val.setFont(font)
        self.IE_ratio_val.setObjectName("IE_ratio_val")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.IE_ratio_val)
        self.peak_pressure_lbl = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.peak_pressure_lbl.setFont(font)
        self.peak_pressure_lbl.setObjectName("peak_pressure_lbl")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.peak_pressure_lbl)
        self.peak_pressure_val = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.peak_pressure_val.setFont(font)
        self.peak_pressure_val.setObjectName("peak_pressure_val")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.peak_pressure_val)
        self.tidal_volume_lbl = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.tidal_volume_lbl.setFont(font)
        self.tidal_volume_lbl.setObjectName("tidal_volume_lbl")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.tidal_volume_lbl)
        self.tidal_volume_val = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.tidal_volume_val.setFont(font)
        self.tidal_volume_val.setObjectName("tidal_volume_val")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tidal_volume_val)
        self.exhale_time_val = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.exhale_time_val.setFont(font)
        self.exhale_time_val.setObjectName("exhale_time_val")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.exhale_time_val)
        self.verticalLayout_2.addLayout(self.formLayout_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        Respirador.setCentralWidget(self.centralWidget)

        self.retranslateUi(Respirador)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Respirador)
        Respirador.setTabOrder(self.VCV_inhale_pause_plus, self.VCV_start_btn)
        Respirador.setTabOrder(self.VCV_start_btn, self.VCV_stop_btn)
        Respirador.setTabOrder(self.VCV_stop_btn, self.VCV_flow_minus)
        Respirador.setTabOrder(self.VCV_flow_minus, self.VCV_flow_plus)
        Respirador.setTabOrder(self.VCV_flow_plus, self.VCV_frequency_plus)
        Respirador.setTabOrder(self.VCV_frequency_plus, self.VCV_frequency_minus)
        Respirador.setTabOrder(self.VCV_frequency_minus, self.VCV_volume_plus)
        Respirador.setTabOrder(self.VCV_volume_plus, self.VCV_volume_minus)
        Respirador.setTabOrder(self.VCV_volume_minus, self.PCV_start_btn)
        Respirador.setTabOrder(self.PCV_start_btn, self.PCV_stop_bnt)
        Respirador.setTabOrder(self.PCV_stop_bnt, self.PCV_rise_time_minus)
        Respirador.setTabOrder(self.PCV_rise_time_minus, self.PCV_rise_time_plus)
        Respirador.setTabOrder(self.PCV_rise_time_plus, self.PCV_frequency_minus)
        Respirador.setTabOrder(self.PCV_frequency_minus, self.PCV_frequency_plus)
        Respirador.setTabOrder(self.PCV_frequency_plus, self.PCV_inhale_time_minus)
        Respirador.setTabOrder(self.PCV_inhale_time_minus, self.PCV_inhale_time_plus)
        Respirador.setTabOrder(self.PCV_inhale_time_plus, self.PCV_pressure_minus)
        Respirador.setTabOrder(self.PCV_pressure_minus, self.PCV_pressure_plus)
        Respirador.setTabOrder(self.PCV_pressure_plus, self.PSV_start_btn)
        Respirador.setTabOrder(self.PSV_start_btn, self.PSV_stop_btn)
        Respirador.setTabOrder(self.PSV_stop_btn, self.PSV_pressure_minus)
        Respirador.setTabOrder(self.PSV_pressure_minus, self.PSV_pressure_plus)
        Respirador.setTabOrder(self.PSV_pressure_plus, self.PSV_rise_time_minus)
        Respirador.setTabOrder(self.PSV_rise_time_minus, self.PSV_rise_time_plus)
        Respirador.setTabOrder(self.PSV_rise_time_plus, self.al_volume_minute_chkBox)
        Respirador.setTabOrder(self.al_volume_minute_chkBox, self.al_tidal_volume_max_dSpinBox)
        Respirador.setTabOrder(self.al_tidal_volume_max_dSpinBox, self.al_tidal_volume_ok_btn)
        Respirador.setTabOrder(self.al_tidal_volume_ok_btn, self.al_plateau_pressure_chkBox)
        Respirador.setTabOrder(self.al_plateau_pressure_chkBox, self.al_PEEP_chkBox)
        Respirador.setTabOrder(self.al_PEEP_chkBox, self.al_frequency_chkBox)
        Respirador.setTabOrder(self.al_frequency_chkBox, self.al_tidal_volume_min_dSpinBox)
        Respirador.setTabOrder(self.al_tidal_volume_min_dSpinBox, self.al_tidal_volume_chkBox)
        Respirador.setTabOrder(self.al_tidal_volume_chkBox, self.al_paw_chkBox)
        Respirador.setTabOrder(self.al_paw_chkBox, self.al_flow_chkBox)
        Respirador.setTabOrder(self.al_flow_chkBox, self.al_apnea_chkBox)
        Respirador.setTabOrder(self.al_apnea_chkBox, self.al_volume_minute_min_dSpinBox)
        Respirador.setTabOrder(self.al_volume_minute_min_dSpinBox, self.al_flow_min_dSpinBox)
        Respirador.setTabOrder(self.al_flow_min_dSpinBox, self.al_paw_min_dSpinBox)
        Respirador.setTabOrder(self.al_paw_min_dSpinBox, self.al_plateau_pressure_min_dSpinBox)
        Respirador.setTabOrder(self.al_plateau_pressure_min_dSpinBox, self.al_PEEP_min_dSpinBox)
        Respirador.setTabOrder(self.al_PEEP_min_dSpinBox, self.al_frequency_min_dSpinBox)
        Respirador.setTabOrder(self.al_frequency_min_dSpinBox, self.al_apnea_min_dSpinBox)
        Respirador.setTabOrder(self.al_apnea_min_dSpinBox, self.al_apnea_max_dSpinBox)
        Respirador.setTabOrder(self.al_apnea_max_dSpinBox, self.al_frequency_max_dSpinBox)
        Respirador.setTabOrder(self.al_frequency_max_dSpinBox, self.al_PEEP_max_dSpinBox)
        Respirador.setTabOrder(self.al_PEEP_max_dSpinBox, self.al_plateau_pressure_max_dSpinBox)
        Respirador.setTabOrder(self.al_plateau_pressure_max_dSpinBox, self.al_paw_max_dSpinBox)
        Respirador.setTabOrder(self.al_paw_max_dSpinBox, self.al_flow_max_dSpinBox)
        Respirador.setTabOrder(self.al_flow_max_dSpinBox, self.al_volume_minute_max_dSpinBox)
        Respirador.setTabOrder(self.al_volume_minute_max_dSpinBox, self.al_volume_minute_ok_btn)
        Respirador.setTabOrder(self.al_volume_minute_ok_btn, self.al_flow_ok_btn)
        Respirador.setTabOrder(self.al_flow_ok_btn, self.al_paw_ok_btn)
        Respirador.setTabOrder(self.al_paw_ok_btn, self.al_plateau_pressure_ok_btn)
        Respirador.setTabOrder(self.al_plateau_pressure_ok_btn, self.al_PEEP_ok_btn)
        Respirador.setTabOrder(self.al_PEEP_ok_btn, self.al_frequency_ok_btn)
        Respirador.setTabOrder(self.al_frequency_ok_btn, self.al_apnea_ok_btn)
        Respirador.setTabOrder(self.al_apnea_ok_btn, self.VCV_inhale_pause_btn)
        Respirador.setTabOrder(self.VCV_inhale_pause_btn, self.VCV_inhale_pause_minus)
        Respirador.setTabOrder(self.VCV_inhale_pause_minus, self.tabWidget)
        Respirador.setTabOrder(self.tabWidget, self.PCV_inhale_pause_minus)
        Respirador.setTabOrder(self.PCV_inhale_pause_minus, self.PCV_inhale_pause_btn)
        Respirador.setTabOrder(self.PCV_inhale_pause_btn, self.PCV_inhale_pause_plus)
        Respirador.setTabOrder(self.PCV_inhale_pause_plus, self.PSV_inhale_pause_btn)
        Respirador.setTabOrder(self.PSV_inhale_pause_btn, self.PSV_inhale_pause_minus)
        Respirador.setTabOrder(self.PSV_inhale_pause_minus, self.PSV_inhale_pause_plus)

    def retranslateUi(self, Respirador):
        _translate = QtCore.QCoreApplication.translate
        Respirador.setWindowTitle(_translate("Respirador", "MainWindow"))
        self.VCV_volume_lbl.setText(_translate("Respirador", "Volume"))
        self.VCV_volume_minus.setText(_translate("Respirador", "-"))
        self.VCV_volume_val.setText(_translate("Respirador", "ml"))
        self.VCV_volume_plus.setText(_translate("Respirador", "+"))
        self.VCV_frequency_lbl.setText(_translate("Respirador", "Frequência"))
        self.VCV_frequency_minus.setText(_translate("Respirador", "-"))
        self.VCV_frequency_val.setText(_translate("Respirador", "rpm"))
        self.VCV_frequency_plus.setText(_translate("Respirador", "+"))
        self.VCV_flow_lbl.setText(_translate("Respirador", "Fluxo"))
        self.VCV_flow_minus.setText(_translate("Respirador", "-"))
        self.VCV_flow_val.setText(_translate("Respirador", "L/min"))
        self.VCV_flow_plus.setText(_translate("Respirador", "+"))
        self.VCV_inhale_pause_btn.setText(_translate("Respirador", "Pausa Insp."))
        self.VCV_inhale_pause_minus.setText(_translate("Respirador", "-"))
        self.VCV_inhale_pause_val.setText(_translate("Respirador", "s"))
        self.VCV_inhale_pause_plus.setText(_translate("Respirador", "+"))
        self.VCV_start_btn.setText(_translate("Respirador", "Iniciar VCV"))
        self.VCV_stop_btn.setText(_translate("Respirador", "Parar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VCV_tab), _translate("Respirador", "VCV"))
        self.PCV_pressure_lbl.setText(_translate("Respirador", "Pressão"))
        self.PCV_pressure_minus.setText(_translate("Respirador", "-"))
        self.PCV_pressure_val.setText(_translate("Respirador", "cm H2O"))
        self.PCV_pressure_plus.setText(_translate("Respirador", "+"))
        self.PCV_frequency_lbl.setText(_translate("Respirador", "Frequência"))
        self.PCV_frequency_minus.setText(_translate("Respirador", "-"))
        self.PCV_frequency_val.setText(_translate("Respirador", "rpm"))
        self.PCV_frequency_plus.setText(_translate("Respirador", "+"))
        self.PCV_inhale_time_lbl.setText(_translate("Respirador", "Tempo Insp."))
        self.PCV_inhale_time_minus.setText(_translate("Respirador", "-"))
        self.PCV_inhale_time_val.setText(_translate("Respirador", "s"))
        self.PCV_inhale_time_plus.setText(_translate("Respirador", "+"))
        self.PCV_rise_time_lbl.setText(_translate("Respirador", "Tempo Subida"))
        self.PCV_rise_time_minus.setText(_translate("Respirador", "-"))
        self.PCV_rise_time_val.setText(_translate("Respirador", "s"))
        self.PCV_rise_time_plus.setText(_translate("Respirador", "+"))
        self.PCV_start_btn.setText(_translate("Respirador", "Iniciar PCV"))
        self.PCV_stop_bnt.setText(_translate("Respirador", "Parar PCV"))
        self.PCV_inhale_pause_minus.setText(_translate("Respirador", "-"))
        self.PCV_inhale_pause_val.setText(_translate("Respirador", "s"))
        self.PCV_inhale_pause_plus.setText(_translate("Respirador", "+"))
        self.PCV_inhale_pause_btn.setText(_translate("Respirador", "Pausa Insp."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PCV_tab), _translate("Respirador", "PCV"))
        self.PSV_support_pressure_lbl.setText(_translate("Respirador", "Pressão Suporte"))
        self.PSV_pressure_minus.setText(_translate("Respirador", "-"))
        self.PSV_pressure_val.setText(_translate("Respirador", "cm H2O"))
        self.PSV_pressure_plus.setText(_translate("Respirador", "+"))
        self.PSV_rise_time_lbl.setText(_translate("Respirador", "Tempo Subida"))
        self.PSV_rise_time_minus.setText(_translate("Respirador", "-"))
        self.PSV_rise_time_val.setText(_translate("Respirador", "s"))
        self.PSV_rise_time_plus.setText(_translate("Respirador", "+"))
        self.PSV_start_btn.setText(_translate("Respirador", "Iniciar PSV"))
        self.PSV_stop_btn.setText(_translate("Respirador", "Parar PSV"))
        self.PSV_inhale_pause_minus.setText(_translate("Respirador", "-"))
        self.PSV_inhale_pause_val.setText(_translate("Respirador", "s"))
        self.PSV_inhale_pause_plus.setText(_translate("Respirador", "+"))
        self.PSV_inhale_pause_btn.setText(_translate("Respirador", "Pausa Insp."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PSV_tab), _translate("Respirador", "PSV"))
        self.al_paw_chkBox.setText(_translate("Respirador", "Paw"))
        self.al_apnea_chkBox.setText(_translate("Respirador", "Apneia"))
        self.al_plateau_pressure_chkBox.setText(_translate("Respirador", "Press. Platô"))
        self.al_frequency_chkBox.setText(_translate("Respirador", "Frequência"))
        self.al_paw_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_volume_minute_chkBox.setText(_translate("Respirador", "Volume/min"))
        self.al_tidal_volume_chkBox.setText(_translate("Respirador", "V. Corrente"))
        self.al_tidal_volume_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_flow_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_volume_minute_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_frequency_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_PEEP_chkBox.setText(_translate("Respirador", "PEEP"))
        self.al_flow_chkBox.setText(_translate("Respirador", "Fluxo"))
        self.al_plateau_pressure_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_PEEP_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_apnea_ok_btn.setText(_translate("Respirador", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.alarms_tab), _translate("Respirador", "Alarmes"))
        self.inhale_time_lbl.setText(_translate("Respirador", "Tempo Inspiração"))
        self.inhale_time_val.setText(_translate("Respirador", "TextLabel"))
        self.exhale_time_lbl.setText(_translate("Respirador", "Tempo Expiração"))
        self.IE_ratio_lbl.setText(_translate("Respirador", "Razão I:E"))
        self.IE_ratio_val.setText(_translate("Respirador", "TextLabel"))
        self.peak_pressure_lbl.setText(_translate("Respirador", "Pressão Pico"))
        self.peak_pressure_val.setText(_translate("Respirador", "TextLabel"))
        self.tidal_volume_lbl.setText(_translate("Respirador", "Volume Corrente"))
        self.tidal_volume_val.setText(_translate("Respirador", "TextLabel"))
        self.exhale_time_val.setText(_translate("Respirador", "TextLabel"))

