# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/software-ventilador/ui/GUI_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Respirador(object):
    def setupUi(self, Respirador):
        Respirador.setObjectName("Respirador")
        Respirador.resize(1116, 715)
        Respirador.setMinimumSize(QtCore.QSize(800, 600))
        Respirador.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralWidget = QtWidgets.QWidget(Respirador)
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.volume_graph_VBox = QtWidgets.QVBoxLayout()
        self.volume_graph_VBox.setObjectName("volume_graph_VBox")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.volume_graph_VBox.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.volume_graph_VBox)
        self.flow_graph_VBox = QtWidgets.QVBoxLayout()
        self.flow_graph_VBox.setObjectName("flow_graph_VBox")
        self.verticalLayout_4.addLayout(self.flow_graph_VBox)
        self.pressure_graph_VBox = QtWidgets.QVBoxLayout()
        self.pressure_graph_VBox.setObjectName("pressure_graph_VBox")
        self.verticalLayout_4.addLayout(self.pressure_graph_VBox)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.VCV_tab = QtWidgets.QWidget()
        self.VCV_tab.setObjectName("VCV_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.VCV_tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.VCV_volume_lbl = QtWidgets.QLabel(self.VCV_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VCV_volume_lbl.sizePolicy().hasHeightForWidth())
        self.VCV_volume_lbl.setSizePolicy(sizePolicy)
        self.VCV_volume_lbl.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.VCV_volume_lbl.setFont(font)
        self.VCV_volume_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.VCV_volume_lbl.setObjectName("VCV_volume_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.VCV_volume_lbl)
        self.VCV_volume_dSpinBox = QtWidgets.QDoubleSpinBox(self.VCV_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VCV_volume_dSpinBox.sizePolicy().hasHeightForWidth())
        self.VCV_volume_dSpinBox.setSizePolicy(sizePolicy)
        self.VCV_volume_dSpinBox.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.VCV_volume_dSpinBox.setFont(font)
        self.VCV_volume_dSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.VCV_volume_dSpinBox.setDecimals(0)
        self.VCV_volume_dSpinBox.setMaximum(1000.0)
        self.VCV_volume_dSpinBox.setSingleStep(5.0)
        self.VCV_volume_dSpinBox.setObjectName("VCV_volume_dSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.VCV_volume_dSpinBox)
        self.VCV_frequency_lbl = QtWidgets.QLabel(self.VCV_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VCV_frequency_lbl.sizePolicy().hasHeightForWidth())
        self.VCV_frequency_lbl.setSizePolicy(sizePolicy)
        self.VCV_frequency_lbl.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.VCV_frequency_lbl.setFont(font)
        self.VCV_frequency_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.VCV_frequency_lbl.setObjectName("VCV_frequency_lbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.VCV_frequency_lbl)
        self.VCV_frequency_dSpinBox = QtWidgets.QDoubleSpinBox(self.VCV_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VCV_frequency_dSpinBox.sizePolicy().hasHeightForWidth())
        self.VCV_frequency_dSpinBox.setSizePolicy(sizePolicy)
        self.VCV_frequency_dSpinBox.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.VCV_frequency_dSpinBox.setFont(font)
        self.VCV_frequency_dSpinBox.setWrapping(False)
        self.VCV_frequency_dSpinBox.setFrame(True)
        self.VCV_frequency_dSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.VCV_frequency_dSpinBox.setDecimals(0)
        self.VCV_frequency_dSpinBox.setMaximum(30.0)
        self.VCV_frequency_dSpinBox.setObjectName("VCV_frequency_dSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.VCV_frequency_dSpinBox)
        self.VCV_flow_lbl = QtWidgets.QLabel(self.VCV_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VCV_flow_lbl.sizePolicy().hasHeightForWidth())
        self.VCV_flow_lbl.setSizePolicy(sizePolicy)
        self.VCV_flow_lbl.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.VCV_flow_lbl.setFont(font)
        self.VCV_flow_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.VCV_flow_lbl.setObjectName("VCV_flow_lbl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.VCV_flow_lbl)
        self.VCV_flow_dSpinBox = QtWidgets.QDoubleSpinBox(self.VCV_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VCV_flow_dSpinBox.sizePolicy().hasHeightForWidth())
        self.VCV_flow_dSpinBox.setSizePolicy(sizePolicy)
        self.VCV_flow_dSpinBox.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.VCV_flow_dSpinBox.setFont(font)
        self.VCV_flow_dSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.VCV_flow_dSpinBox.setDecimals(0)
        self.VCV_flow_dSpinBox.setMaximum(60.0)
        self.VCV_flow_dSpinBox.setObjectName("VCV_flow_dSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.VCV_flow_dSpinBox)
        self.verticalLayout_9.addLayout(self.formLayout)
        self.tabWidget.addTab(self.VCV_tab, "")
        self.PCV_tab = QtWidgets.QWidget()
        self.PCV_tab.setObjectName("PCV_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.PCV_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.PCV_pressure_lbl = QtWidgets.QLabel(self.PCV_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PCV_pressure_lbl.setFont(font)
        self.PCV_pressure_lbl.setObjectName("PCV_pressure_lbl")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.PCV_pressure_lbl)
        self.PCV_pressure_dSpinBox = QtWidgets.QDoubleSpinBox(self.PCV_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PCV_pressure_dSpinBox.setFont(font)
        self.PCV_pressure_dSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.PCV_pressure_dSpinBox.setObjectName("PCV_pressure_dSpinBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PCV_pressure_dSpinBox)
        self.PCV_frequency_lbl = QtWidgets.QLabel(self.PCV_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PCV_frequency_lbl.setFont(font)
        self.PCV_frequency_lbl.setObjectName("PCV_frequency_lbl")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.PCV_frequency_lbl)
        self.PCV_frequency_dSpinBox = QtWidgets.QDoubleSpinBox(self.PCV_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PCV_frequency_dSpinBox.setFont(font)
        self.PCV_frequency_dSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.PCV_frequency_dSpinBox.setObjectName("PCV_frequency_dSpinBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PCV_frequency_dSpinBox)
        self.PCV_inhale_time_lbl = QtWidgets.QLabel(self.PCV_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PCV_inhale_time_lbl.setFont(font)
        self.PCV_inhale_time_lbl.setObjectName("PCV_inhale_time_lbl")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.PCV_inhale_time_lbl)
        self.PCV_inhale_time_dSpinBox = QtWidgets.QDoubleSpinBox(self.PCV_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PCV_inhale_time_dSpinBox.setFont(font)
        self.PCV_inhale_time_dSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.PCV_inhale_time_dSpinBox.setObjectName("PCV_inhale_time_dSpinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PCV_inhale_time_dSpinBox)
        self.PCV_rise_time_lbl = QtWidgets.QLabel(self.PCV_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PCV_rise_time_lbl.setFont(font)
        self.PCV_rise_time_lbl.setObjectName("PCV_rise_time_lbl")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.PCV_rise_time_lbl)
        self.PCV_rise_time_dSpinBox = QtWidgets.QDoubleSpinBox(self.PCV_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PCV_rise_time_dSpinBox.setFont(font)
        self.PCV_rise_time_dSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.PCV_rise_time_dSpinBox.setObjectName("PCV_rise_time_dSpinBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.PCV_rise_time_dSpinBox)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.tabWidget.addTab(self.PCV_tab, "")
        self.PSV_tab = QtWidgets.QWidget()
        self.PSV_tab.setObjectName("PSV_tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.PSV_tab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.PSV_support_pressure_dSpinBox = QtWidgets.QDoubleSpinBox(self.PSV_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PSV_support_pressure_dSpinBox.setFont(font)
        self.PSV_support_pressure_dSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.PSV_support_pressure_dSpinBox.setObjectName("PSV_support_pressure_dSpinBox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PSV_support_pressure_dSpinBox)
        self.PSV_support_pressure_lbl = QtWidgets.QLabel(self.PSV_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PSV_support_pressure_lbl.setFont(font)
        self.PSV_support_pressure_lbl.setObjectName("PSV_support_pressure_lbl")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.PSV_support_pressure_lbl)
        self.PSV_rise_time_dSpinBox = QtWidgets.QDoubleSpinBox(self.PSV_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PSV_rise_time_dSpinBox.setFont(font)
        self.PSV_rise_time_dSpinBox.setObjectName("PSV_rise_time_dSpinBox")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PSV_rise_time_dSpinBox)
        self.PSV_rise_time_lbl = QtWidgets.QLabel(self.PSV_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PSV_rise_time_lbl.setFont(font)
        self.PSV_rise_time_lbl.setObjectName("PSV_rise_time_lbl")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.PSV_rise_time_lbl)
        self.verticalLayout_10.addLayout(self.formLayout_4)
        self.tabWidget.addTab(self.PSV_tab, "")
        self.manual_tab = QtWidgets.QWidget()
        self.manual_tab.setObjectName("manual_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.manual_tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.piston_auto_btn = QtWidgets.QPushButton(self.manual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.piston_auto_btn.sizePolicy().hasHeightForWidth())
        self.piston_auto_btn.setSizePolicy(sizePolicy)
        self.piston_auto_btn.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(20)
        self.piston_auto_btn.setFont(font)
        self.piston_auto_btn.setObjectName("piston_auto_btn")
        self.gridLayout.addWidget(self.piston_auto_btn, 0, 1, 1, 1)
        self.piston_raise_btn = QtWidgets.QPushButton(self.manual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.piston_raise_btn.sizePolicy().hasHeightForWidth())
        self.piston_raise_btn.setSizePolicy(sizePolicy)
        self.piston_raise_btn.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(20)
        self.piston_raise_btn.setFont(font)
        self.piston_raise_btn.setObjectName("piston_raise_btn")
        self.gridLayout.addWidget(self.piston_raise_btn, 1, 0, 1, 1)
        self.piston_lower_btn = QtWidgets.QPushButton(self.manual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.piston_lower_btn.sizePolicy().hasHeightForWidth())
        self.piston_lower_btn.setSizePolicy(sizePolicy)
        self.piston_lower_btn.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(20)
        self.piston_lower_btn.setFont(font)
        self.piston_lower_btn.setObjectName("piston_lower_btn")
        self.gridLayout.addWidget(self.piston_lower_btn, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.piston_top_delay_label = QtWidgets.QLabel(self.manual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.piston_top_delay_label.sizePolicy().hasHeightForWidth())
        self.piston_top_delay_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(20)
        self.piston_top_delay_label.setFont(font)
        self.piston_top_delay_label.setAlignment(QtCore.Qt.AlignCenter)
        self.piston_top_delay_label.setObjectName("piston_top_delay_label")
        self.verticalLayout_8.addWidget(self.piston_top_delay_label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.piston_top_delay_minus_btn = QtWidgets.QPushButton(self.manual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.piston_top_delay_minus_btn.sizePolicy().hasHeightForWidth())
        self.piston_top_delay_minus_btn.setSizePolicy(sizePolicy)
        self.piston_top_delay_minus_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(30)
        self.piston_top_delay_minus_btn.setFont(font)
        self.piston_top_delay_minus_btn.setObjectName("piston_top_delay_minus_btn")
        self.horizontalLayout_5.addWidget(self.piston_top_delay_minus_btn)
        self.piston_top_delay_dSpinBox = QtWidgets.QDoubleSpinBox(self.manual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.piston_top_delay_dSpinBox.sizePolicy().hasHeightForWidth())
        self.piston_top_delay_dSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(20)
        self.piston_top_delay_dSpinBox.setFont(font)
        self.piston_top_delay_dSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.piston_top_delay_dSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.piston_top_delay_dSpinBox.setDecimals(1)
        self.piston_top_delay_dSpinBox.setSingleStep(0.1)
        self.piston_top_delay_dSpinBox.setObjectName("piston_top_delay_dSpinBox")
        self.horizontalLayout_5.addWidget(self.piston_top_delay_dSpinBox)
        self.piston_top_delay_plus_btn = QtWidgets.QPushButton(self.manual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.piston_top_delay_plus_btn.sizePolicy().hasHeightForWidth())
        self.piston_top_delay_plus_btn.setSizePolicy(sizePolicy)
        self.piston_top_delay_plus_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.piston_top_delay_plus_btn.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(30)
        self.piston_top_delay_plus_btn.setFont(font)
        self.piston_top_delay_plus_btn.setObjectName("piston_top_delay_plus_btn")
        self.horizontalLayout_5.addWidget(self.piston_top_delay_plus_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.piston_bottom_delay_label = QtWidgets.QLabel(self.manual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.piston_bottom_delay_label.sizePolicy().hasHeightForWidth())
        self.piston_bottom_delay_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(20)
        self.piston_bottom_delay_label.setFont(font)
        self.piston_bottom_delay_label.setAlignment(QtCore.Qt.AlignCenter)
        self.piston_bottom_delay_label.setObjectName("piston_bottom_delay_label")
        self.verticalLayout_8.addWidget(self.piston_bottom_delay_label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.piston_bottom_delay_minus_btn = QtWidgets.QPushButton(self.manual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.piston_bottom_delay_minus_btn.sizePolicy().hasHeightForWidth())
        self.piston_bottom_delay_minus_btn.setSizePolicy(sizePolicy)
        self.piston_bottom_delay_minus_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(30)
        self.piston_bottom_delay_minus_btn.setFont(font)
        self.piston_bottom_delay_minus_btn.setObjectName("piston_bottom_delay_minus_btn")
        self.horizontalLayout_6.addWidget(self.piston_bottom_delay_minus_btn)
        self.piston_bottom_delay_dSpinBox = QtWidgets.QDoubleSpinBox(self.manual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.piston_bottom_delay_dSpinBox.sizePolicy().hasHeightForWidth())
        self.piston_bottom_delay_dSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(20)
        self.piston_bottom_delay_dSpinBox.setFont(font)
        self.piston_bottom_delay_dSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.piston_bottom_delay_dSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.piston_bottom_delay_dSpinBox.setDecimals(1)
        self.piston_bottom_delay_dSpinBox.setSingleStep(0.1)
        self.piston_bottom_delay_dSpinBox.setObjectName("piston_bottom_delay_dSpinBox")
        self.horizontalLayout_6.addWidget(self.piston_bottom_delay_dSpinBox)
        self.piston_bottom_delay_plus_btn = QtWidgets.QPushButton(self.manual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.piston_bottom_delay_plus_btn.sizePolicy().hasHeightForWidth())
        self.piston_bottom_delay_plus_btn.setSizePolicy(sizePolicy)
        self.piston_bottom_delay_plus_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(30)
        self.piston_bottom_delay_plus_btn.setFont(font)
        self.piston_bottom_delay_plus_btn.setObjectName("piston_bottom_delay_plus_btn")
        self.horizontalLayout_6.addWidget(self.piston_bottom_delay_plus_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.manual_tab, "")
        self.alarms_tab = QtWidgets.QWidget()
        self.alarms_tab.setObjectName("alarms_tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.alarms_tab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.al_volume_minute_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_volume_minute_chkBox.setFont(font)
        self.al_volume_minute_chkBox.setObjectName("al_volume_minute_chkBox")
        self.gridLayout_2.addWidget(self.al_volume_minute_chkBox, 2, 0, 1, 1)
        self.al_tidal_volume_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_tidal_volume_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_tidal_volume_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_tidal_volume_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_tidal_volume_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_tidal_volume_max_dSpinBox.setFont(font)
        self.al_tidal_volume_max_dSpinBox.setDecimals(1)
        self.al_tidal_volume_max_dSpinBox.setMaximum(100000.0)
        self.al_tidal_volume_max_dSpinBox.setSingleStep(0.1)
        self.al_tidal_volume_max_dSpinBox.setObjectName("al_tidal_volume_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_tidal_volume_max_dSpinBox, 1, 2, 1, 1)
        self.al_tidal_volume_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_tidal_volume_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_tidal_volume_ok_btn.setSizePolicy(sizePolicy)
        self.al_tidal_volume_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_tidal_volume_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_tidal_volume_ok_btn.setFont(font)
        self.al_tidal_volume_ok_btn.setObjectName("al_tidal_volume_ok_btn")
        self.gridLayout_2.addWidget(self.al_tidal_volume_ok_btn, 1, 3, 1, 1)
        self.al_plateau_pressure_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_plateau_pressure_chkBox.setFont(font)
        self.al_plateau_pressure_chkBox.setObjectName("al_plateau_pressure_chkBox")
        self.gridLayout_2.addWidget(self.al_plateau_pressure_chkBox, 5, 0, 1, 1)
        self.al_PEEP_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_PEEP_chkBox.setFont(font)
        self.al_PEEP_chkBox.setObjectName("al_PEEP_chkBox")
        self.gridLayout_2.addWidget(self.al_PEEP_chkBox, 6, 0, 1, 1)
        self.al_frequency_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_frequency_chkBox.setFont(font)
        self.al_frequency_chkBox.setObjectName("al_frequency_chkBox")
        self.gridLayout_2.addWidget(self.al_frequency_chkBox, 7, 0, 1, 1)
        self.al_tidal_volume_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_tidal_volume_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_tidal_volume_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_tidal_volume_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_tidal_volume_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_tidal_volume_min_dSpinBox.setFont(font)
        self.al_tidal_volume_min_dSpinBox.setDecimals(1)
        self.al_tidal_volume_min_dSpinBox.setMaximum(100000.0)
        self.al_tidal_volume_min_dSpinBox.setSingleStep(0.1)
        self.al_tidal_volume_min_dSpinBox.setObjectName("al_tidal_volume_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_tidal_volume_min_dSpinBox, 1, 1, 1, 1)
        self.al_tidal_volume_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_tidal_volume_chkBox.setFont(font)
        self.al_tidal_volume_chkBox.setObjectName("al_tidal_volume_chkBox")
        self.gridLayout_2.addWidget(self.al_tidal_volume_chkBox, 1, 0, 1, 1)
        self.al_paw_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_paw_chkBox.setFont(font)
        self.al_paw_chkBox.setObjectName("al_paw_chkBox")
        self.gridLayout_2.addWidget(self.al_paw_chkBox, 4, 0, 1, 1)
        self.al_flow_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_flow_chkBox.setFont(font)
        self.al_flow_chkBox.setObjectName("al_flow_chkBox")
        self.gridLayout_2.addWidget(self.al_flow_chkBox, 3, 0, 1, 1)
        self.al_apnea_chkBox = QtWidgets.QCheckBox(self.alarms_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_apnea_chkBox.setFont(font)
        self.al_apnea_chkBox.setObjectName("al_apnea_chkBox")
        self.gridLayout_2.addWidget(self.al_apnea_chkBox, 8, 0, 1, 1)
        self.al_volume_minute_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_volume_minute_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_volume_minute_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_volume_minute_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_volume_minute_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_volume_minute_min_dSpinBox.setFont(font)
        self.al_volume_minute_min_dSpinBox.setDecimals(1)
        self.al_volume_minute_min_dSpinBox.setMaximum(100000.0)
        self.al_volume_minute_min_dSpinBox.setSingleStep(0.1)
        self.al_volume_minute_min_dSpinBox.setObjectName("al_volume_minute_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_volume_minute_min_dSpinBox, 2, 1, 1, 1)
        self.al_flow_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_flow_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_flow_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_flow_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_flow_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_flow_min_dSpinBox.setFont(font)
        self.al_flow_min_dSpinBox.setDecimals(1)
        self.al_flow_min_dSpinBox.setMaximum(100000.0)
        self.al_flow_min_dSpinBox.setSingleStep(0.1)
        self.al_flow_min_dSpinBox.setObjectName("al_flow_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_flow_min_dSpinBox, 3, 1, 1, 1)
        self.al_paw_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_paw_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_paw_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_paw_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_paw_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_paw_min_dSpinBox.setFont(font)
        self.al_paw_min_dSpinBox.setDecimals(1)
        self.al_paw_min_dSpinBox.setMaximum(100000.0)
        self.al_paw_min_dSpinBox.setSingleStep(0.1)
        self.al_paw_min_dSpinBox.setObjectName("al_paw_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_paw_min_dSpinBox, 4, 1, 1, 1)
        self.al_plateau_pressure_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_plateau_pressure_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_plateau_pressure_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_plateau_pressure_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_plateau_pressure_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_plateau_pressure_min_dSpinBox.setFont(font)
        self.al_plateau_pressure_min_dSpinBox.setDecimals(1)
        self.al_plateau_pressure_min_dSpinBox.setMaximum(100000.0)
        self.al_plateau_pressure_min_dSpinBox.setSingleStep(0.1)
        self.al_plateau_pressure_min_dSpinBox.setObjectName("al_plateau_pressure_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_plateau_pressure_min_dSpinBox, 5, 1, 1, 1)
        self.al_PEEP_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_PEEP_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_PEEP_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_PEEP_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_PEEP_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_PEEP_min_dSpinBox.setFont(font)
        self.al_PEEP_min_dSpinBox.setDecimals(1)
        self.al_PEEP_min_dSpinBox.setMaximum(100000.0)
        self.al_PEEP_min_dSpinBox.setSingleStep(0.1)
        self.al_PEEP_min_dSpinBox.setObjectName("al_PEEP_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_PEEP_min_dSpinBox, 6, 1, 1, 1)
        self.al_frequency_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_frequency_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_frequency_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_frequency_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_frequency_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_frequency_min_dSpinBox.setFont(font)
        self.al_frequency_min_dSpinBox.setDecimals(1)
        self.al_frequency_min_dSpinBox.setMaximum(100000.0)
        self.al_frequency_min_dSpinBox.setSingleStep(0.1)
        self.al_frequency_min_dSpinBox.setObjectName("al_frequency_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_frequency_min_dSpinBox, 7, 1, 1, 1)
        self.al_apnea_min_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_apnea_min_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_apnea_min_dSpinBox.setSizePolicy(sizePolicy)
        self.al_apnea_min_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_apnea_min_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_apnea_min_dSpinBox.setFont(font)
        self.al_apnea_min_dSpinBox.setDecimals(1)
        self.al_apnea_min_dSpinBox.setMaximum(100000.0)
        self.al_apnea_min_dSpinBox.setSingleStep(0.1)
        self.al_apnea_min_dSpinBox.setObjectName("al_apnea_min_dSpinBox")
        self.gridLayout_2.addWidget(self.al_apnea_min_dSpinBox, 8, 1, 1, 1)
        self.al_apnea_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_apnea_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_apnea_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_apnea_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_apnea_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_apnea_max_dSpinBox.setFont(font)
        self.al_apnea_max_dSpinBox.setDecimals(1)
        self.al_apnea_max_dSpinBox.setMaximum(100000.0)
        self.al_apnea_max_dSpinBox.setSingleStep(0.1)
        self.al_apnea_max_dSpinBox.setObjectName("al_apnea_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_apnea_max_dSpinBox, 8, 2, 1, 1)
        self.al_frequency_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_frequency_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_frequency_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_frequency_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_frequency_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_frequency_max_dSpinBox.setFont(font)
        self.al_frequency_max_dSpinBox.setDecimals(1)
        self.al_frequency_max_dSpinBox.setMaximum(100000.0)
        self.al_frequency_max_dSpinBox.setSingleStep(0.1)
        self.al_frequency_max_dSpinBox.setObjectName("al_frequency_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_frequency_max_dSpinBox, 7, 2, 1, 1)
        self.al_PEEP_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_PEEP_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_PEEP_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_PEEP_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_PEEP_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_PEEP_max_dSpinBox.setFont(font)
        self.al_PEEP_max_dSpinBox.setDecimals(1)
        self.al_PEEP_max_dSpinBox.setMaximum(100000.0)
        self.al_PEEP_max_dSpinBox.setSingleStep(0.1)
        self.al_PEEP_max_dSpinBox.setObjectName("al_PEEP_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_PEEP_max_dSpinBox, 6, 2, 1, 1)
        self.al_plateau_pressure_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_plateau_pressure_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_plateau_pressure_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_plateau_pressure_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_plateau_pressure_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_plateau_pressure_max_dSpinBox.setFont(font)
        self.al_plateau_pressure_max_dSpinBox.setDecimals(1)
        self.al_plateau_pressure_max_dSpinBox.setMaximum(100000.0)
        self.al_plateau_pressure_max_dSpinBox.setSingleStep(0.1)
        self.al_plateau_pressure_max_dSpinBox.setObjectName("al_plateau_pressure_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_plateau_pressure_max_dSpinBox, 5, 2, 1, 1)
        self.al_paw_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_paw_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_paw_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_paw_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_paw_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_paw_max_dSpinBox.setFont(font)
        self.al_paw_max_dSpinBox.setDecimals(1)
        self.al_paw_max_dSpinBox.setMaximum(100000.0)
        self.al_paw_max_dSpinBox.setSingleStep(0.1)
        self.al_paw_max_dSpinBox.setObjectName("al_paw_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_paw_max_dSpinBox, 4, 2, 1, 1)
        self.al_flow_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_flow_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_flow_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_flow_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_flow_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_flow_max_dSpinBox.setFont(font)
        self.al_flow_max_dSpinBox.setDecimals(1)
        self.al_flow_max_dSpinBox.setMaximum(100000.0)
        self.al_flow_max_dSpinBox.setSingleStep(0.1)
        self.al_flow_max_dSpinBox.setObjectName("al_flow_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_flow_max_dSpinBox, 3, 2, 1, 1)
        self.al_volume_minute_max_dSpinBox = QtWidgets.QDoubleSpinBox(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_volume_minute_max_dSpinBox.sizePolicy().hasHeightForWidth())
        self.al_volume_minute_max_dSpinBox.setSizePolicy(sizePolicy)
        self.al_volume_minute_max_dSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.al_volume_minute_max_dSpinBox.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_volume_minute_max_dSpinBox.setFont(font)
        self.al_volume_minute_max_dSpinBox.setDecimals(1)
        self.al_volume_minute_max_dSpinBox.setMaximum(100000.0)
        self.al_volume_minute_max_dSpinBox.setSingleStep(0.1)
        self.al_volume_minute_max_dSpinBox.setObjectName("al_volume_minute_max_dSpinBox")
        self.gridLayout_2.addWidget(self.al_volume_minute_max_dSpinBox, 2, 2, 1, 1)
        self.al_volume_minute_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_volume_minute_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_volume_minute_ok_btn.setSizePolicy(sizePolicy)
        self.al_volume_minute_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_volume_minute_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_volume_minute_ok_btn.setFont(font)
        self.al_volume_minute_ok_btn.setObjectName("al_volume_minute_ok_btn")
        self.gridLayout_2.addWidget(self.al_volume_minute_ok_btn, 2, 3, 1, 1)
        self.al_flow_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_flow_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_flow_ok_btn.setSizePolicy(sizePolicy)
        self.al_flow_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_flow_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_flow_ok_btn.setFont(font)
        self.al_flow_ok_btn.setObjectName("al_flow_ok_btn")
        self.gridLayout_2.addWidget(self.al_flow_ok_btn, 3, 3, 1, 1)
        self.al_paw_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_paw_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_paw_ok_btn.setSizePolicy(sizePolicy)
        self.al_paw_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_paw_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_paw_ok_btn.setFont(font)
        self.al_paw_ok_btn.setObjectName("al_paw_ok_btn")
        self.gridLayout_2.addWidget(self.al_paw_ok_btn, 4, 3, 1, 1)
        self.al_plateau_pressure_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_plateau_pressure_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_plateau_pressure_ok_btn.setSizePolicy(sizePolicy)
        self.al_plateau_pressure_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_plateau_pressure_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_plateau_pressure_ok_btn.setFont(font)
        self.al_plateau_pressure_ok_btn.setObjectName("al_plateau_pressure_ok_btn")
        self.gridLayout_2.addWidget(self.al_plateau_pressure_ok_btn, 5, 3, 1, 1)
        self.al_PEEP_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_PEEP_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_PEEP_ok_btn.setSizePolicy(sizePolicy)
        self.al_PEEP_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_PEEP_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_PEEP_ok_btn.setFont(font)
        self.al_PEEP_ok_btn.setObjectName("al_PEEP_ok_btn")
        self.gridLayout_2.addWidget(self.al_PEEP_ok_btn, 6, 3, 1, 1)
        self.al_frequency_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_frequency_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_frequency_ok_btn.setSizePolicy(sizePolicy)
        self.al_frequency_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_frequency_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_frequency_ok_btn.setFont(font)
        self.al_frequency_ok_btn.setObjectName("al_frequency_ok_btn")
        self.gridLayout_2.addWidget(self.al_frequency_ok_btn, 7, 3, 1, 1)
        self.al_apnea_ok_btn = QtWidgets.QPushButton(self.alarms_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.al_apnea_ok_btn.sizePolicy().hasHeightForWidth())
        self.al_apnea_ok_btn.setSizePolicy(sizePolicy)
        self.al_apnea_ok_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.al_apnea_ok_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.al_apnea_ok_btn.setFont(font)
        self.al_apnea_ok_btn.setObjectName("al_apnea_ok_btn")
        self.gridLayout_2.addWidget(self.al_apnea_ok_btn, 8, 3, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.alarms_tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mode_STOP_btn = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_STOP_btn.sizePolicy().hasHeightForWidth())
        self.mode_STOP_btn.setSizePolicy(sizePolicy)
        self.mode_STOP_btn.setMinimumSize(QtCore.QSize(90, 50))
        self.mode_STOP_btn.setSizeIncrement(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mode_STOP_btn.setFont(font)
        self.mode_STOP_btn.setObjectName("mode_STOP_btn")
        self.gridLayout_3.addWidget(self.mode_STOP_btn, 1, 3, 1, 1)
        self.mode_PSV_btn = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_PSV_btn.sizePolicy().hasHeightForWidth())
        self.mode_PSV_btn.setSizePolicy(sizePolicy)
        self.mode_PSV_btn.setMinimumSize(QtCore.QSize(90, 50))
        self.mode_PSV_btn.setSizeIncrement(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mode_PSV_btn.setFont(font)
        self.mode_PSV_btn.setObjectName("mode_PSV_btn")
        self.gridLayout_3.addWidget(self.mode_PSV_btn, 1, 2, 1, 1)
        self.mode_PCV_btn = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_PCV_btn.sizePolicy().hasHeightForWidth())
        self.mode_PCV_btn.setSizePolicy(sizePolicy)
        self.mode_PCV_btn.setMinimumSize(QtCore.QSize(90, 50))
        self.mode_PCV_btn.setSizeIncrement(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mode_PCV_btn.setFont(font)
        self.mode_PCV_btn.setObjectName("mode_PCV_btn")
        self.gridLayout_3.addWidget(self.mode_PCV_btn, 1, 1, 1, 1)
        self.mode_VCV_btn = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_VCV_btn.sizePolicy().hasHeightForWidth())
        self.mode_VCV_btn.setSizePolicy(sizePolicy)
        self.mode_VCV_btn.setMinimumSize(QtCore.QSize(90, 50))
        self.mode_VCV_btn.setSizeIncrement(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(20)
        self.mode_VCV_btn.setFont(font)
        self.mode_VCV_btn.setObjectName("mode_VCV_btn")
        self.gridLayout_3.addWidget(self.mode_VCV_btn, 1, 0, 1, 1)
        self.startup_btn = QtWidgets.QPushButton(self.centralWidget)
        self.startup_btn.setMinimumSize(QtCore.QSize(90, 50))
        self.startup_btn.setSizeIncrement(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.startup_btn.setFont(font)
        self.startup_btn.setObjectName("startup_btn")
        self.gridLayout_3.addWidget(self.startup_btn, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.inhale_pause_btn = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inhale_pause_btn.sizePolicy().hasHeightForWidth())
        self.inhale_pause_btn.setSizePolicy(sizePolicy)
        self.inhale_pause_btn.setMinimumSize(QtCore.QSize(50, 30))
        self.inhale_pause_btn.setObjectName("inhale_pause_btn")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inhale_pause_btn)
        self.inhale_pause_dSpinBox = QtWidgets.QDoubleSpinBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inhale_pause_dSpinBox.setFont(font)
        self.inhale_pause_dSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.inhale_pause_dSpinBox.setObjectName("inhale_pause_dSpinBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inhale_pause_dSpinBox)
        self.inhale_time_lbl = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inhale_time_lbl.setFont(font)
        self.inhale_time_lbl.setObjectName("inhale_time_lbl")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.inhale_time_lbl)
        self.inhale_time_val = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inhale_time_val.setFont(font)
        self.inhale_time_val.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inhale_time_val.setFrameShadow(QtWidgets.QFrame.Plain)
        self.inhale_time_val.setObjectName("inhale_time_val")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inhale_time_val)
        self.exhale_time_lbl = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exhale_time_lbl.setFont(font)
        self.exhale_time_lbl.setObjectName("exhale_time_lbl")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.exhale_time_lbl)
        self.exhale_time_val = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exhale_time_val.setFont(font)
        self.exhale_time_val.setObjectName("exhale_time_val")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.exhale_time_val)
        self.IE_ratio_lbl = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.IE_ratio_lbl.setFont(font)
        self.IE_ratio_lbl.setObjectName("IE_ratio_lbl")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.IE_ratio_lbl)
        self.IE_ratio_val = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.IE_ratio_val.setFont(font)
        self.IE_ratio_val.setObjectName("IE_ratio_val")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.IE_ratio_val)
        self.peak_pressure_lbl = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.peak_pressure_lbl.setFont(font)
        self.peak_pressure_lbl.setObjectName("peak_pressure_lbl")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.peak_pressure_lbl)
        self.peak_pressure_val = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.peak_pressure_val.setFont(font)
        self.peak_pressure_val.setObjectName("peak_pressure_val")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.peak_pressure_val)
        self.tidal_volume_lbl = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tidal_volume_lbl.setFont(font)
        self.tidal_volume_lbl.setObjectName("tidal_volume_lbl")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.tidal_volume_lbl)
        self.tidal_volume_val = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tidal_volume_val.setFont(font)
        self.tidal_volume_val.setObjectName("tidal_volume_val")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tidal_volume_val)
        self.verticalLayout_2.addLayout(self.formLayout_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        Respirador.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Respirador)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1116, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuPrefer_ncias = QtWidgets.QMenu(self.menuBar)
        self.menuPrefer_ncias.setObjectName("menuPrefer_ncias")
        Respirador.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(Respirador)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(Respirador)
        self.actionAbout.setObjectName("actionAbout")
        self.actionGraficos = QtWidgets.QAction(Respirador)
        self.actionGraficos.setObjectName("actionGraficos")
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionExit)
        self.menuPrefer_ncias.addAction(self.actionGraficos)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuPrefer_ncias.menuAction())

        self.retranslateUi(Respirador)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Respirador)

    def retranslateUi(self, Respirador):
        _translate = QtCore.QCoreApplication.translate
        Respirador.setWindowTitle(_translate("Respirador", "MainWindow"))
        self.VCV_volume_lbl.setText(_translate("Respirador", "Volume"))
        self.VCV_volume_dSpinBox.setSuffix(_translate("Respirador", " ml"))
        self.VCV_frequency_lbl.setText(_translate("Respirador", "Frequência"))
        self.VCV_frequency_dSpinBox.setSuffix(_translate("Respirador", " rpm"))
        self.VCV_flow_lbl.setText(_translate("Respirador", "Fluxo"))
        self.VCV_flow_dSpinBox.setSuffix(_translate("Respirador", " l/min"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VCV_tab), _translate("Respirador", "VCV"))
        self.PCV_pressure_lbl.setText(_translate("Respirador", "Pressão"))
        self.PCV_pressure_dSpinBox.setSuffix(_translate("Respirador", " cm H2O"))
        self.PCV_frequency_lbl.setText(_translate("Respirador", "Frequência"))
        self.PCV_frequency_dSpinBox.setSuffix(_translate("Respirador", " rpm"))
        self.PCV_inhale_time_lbl.setText(_translate("Respirador", "Tempo Inspiração"))
        self.PCV_inhale_time_dSpinBox.setSuffix(_translate("Respirador", " s"))
        self.PCV_rise_time_lbl.setText(_translate("Respirador", "Tempo Subida"))
        self.PCV_rise_time_dSpinBox.setSuffix(_translate("Respirador", " s"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PCV_tab), _translate("Respirador", "PCV"))
        self.PSV_support_pressure_dSpinBox.setSuffix(_translate("Respirador", " cm H2O"))
        self.PSV_support_pressure_lbl.setText(_translate("Respirador", "Pressão Suporte"))
        self.PSV_rise_time_dSpinBox.setSuffix(_translate("Respirador", " s"))
        self.PSV_rise_time_lbl.setText(_translate("Respirador", "Tempo Subida"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PSV_tab), _translate("Respirador", "PSV"))
        self.piston_auto_btn.setText(_translate("Respirador", "Auto"))
        self.piston_raise_btn.setText(_translate("Respirador", "Sobe"))
        self.piston_lower_btn.setText(_translate("Respirador", "Desce"))
        self.piston_top_delay_label.setText(_translate("Respirador", "Descanso Alto"))
        self.piston_top_delay_minus_btn.setText(_translate("Respirador", "-"))
        self.piston_top_delay_dSpinBox.setSuffix(_translate("Respirador", " s"))
        self.piston_top_delay_plus_btn.setText(_translate("Respirador", "+"))
        self.piston_bottom_delay_label.setText(_translate("Respirador", "Descanso Baixo"))
        self.piston_bottom_delay_minus_btn.setText(_translate("Respirador", "-"))
        self.piston_bottom_delay_dSpinBox.setSuffix(_translate("Respirador", " s"))
        self.piston_bottom_delay_plus_btn.setText(_translate("Respirador", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manual_tab), _translate("Respirador", "Manual"))
        self.al_volume_minute_chkBox.setText(_translate("Respirador", "Volume/min"))
        self.al_tidal_volume_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_plateau_pressure_chkBox.setText(_translate("Respirador", "Press. Platô"))
        self.al_PEEP_chkBox.setText(_translate("Respirador", "PEEP"))
        self.al_frequency_chkBox.setText(_translate("Respirador", "Frequência"))
        self.al_tidal_volume_chkBox.setText(_translate("Respirador", "V. Corrente"))
        self.al_paw_chkBox.setText(_translate("Respirador", "Paw"))
        self.al_flow_chkBox.setText(_translate("Respirador", "Fluxo"))
        self.al_apnea_chkBox.setText(_translate("Respirador", "Apneia"))
        self.al_volume_minute_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_flow_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_paw_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_plateau_pressure_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_PEEP_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_frequency_ok_btn.setText(_translate("Respirador", "OK"))
        self.al_apnea_ok_btn.setText(_translate("Respirador", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.alarms_tab), _translate("Respirador", "Alarmes"))
        self.mode_STOP_btn.setText(_translate("Respirador", "Parar"))
        self.mode_PSV_btn.setText(_translate("Respirador", "PSV"))
        self.mode_PCV_btn.setText(_translate("Respirador", "PCV"))
        self.mode_VCV_btn.setText(_translate("Respirador", "VCV"))
        self.startup_btn.setText(_translate("Respirador", "Startup"))
        self.inhale_pause_btn.setText(_translate("Respirador", "Pausa Inspiração"))
        self.inhale_pause_dSpinBox.setSuffix(_translate("Respirador", " s"))
        self.inhale_time_lbl.setText(_translate("Respirador", "Tempo Inspiração"))
        self.inhale_time_val.setText(_translate("Respirador", "TextLabel"))
        self.exhale_time_lbl.setText(_translate("Respirador", "Tempo Expiração"))
        self.exhale_time_val.setText(_translate("Respirador", "TextLabel"))
        self.IE_ratio_lbl.setText(_translate("Respirador", "Razão I:E"))
        self.IE_ratio_val.setText(_translate("Respirador", "TextLabel"))
        self.peak_pressure_lbl.setText(_translate("Respirador", "Pressão Pico"))
        self.peak_pressure_val.setText(_translate("Respirador", "TextLabel"))
        self.tidal_volume_lbl.setText(_translate("Respirador", "Volume Corrente"))
        self.tidal_volume_val.setText(_translate("Respirador", "TextLabel"))
        self.menuFile.setTitle(_translate("Respirador", "File"))
        self.menuPrefer_ncias.setTitle(_translate("Respirador", "Preferências"))
        self.actionExit.setText(_translate("Respirador", "Exit"))
        self.actionAbout.setText(_translate("Respirador", "About"))
        self.actionGraficos.setText(_translate("Respirador", "Gráficos"))

